repo_root_path: /home/mk/git_repo/mkos 
app_details:
    - name: config manager
      config_files: 
          - filename: config.yml
            config_file_location: ~/.config/config_manager
            config_file_repo_location: apps/config_manager
    - name: kitty
      config_files: 
          - filename: kitty.conf
            config_file_location: ~/.config/kitty
            config_file_repo_location: apps/kitty
    - name: zsh
      config_files: 
          - filename: .zshrc
            config_file_location: ~
            config_file_repo_location: apps/zsh
    - name: git
      config_files: 
          - filename: .gitconfig
            config_file_location: ~
            config_file_repo_location: apps/git
    - name: nvim
      config_files: 
          - filename: init.lua
            config_file_location: ~/.config/nvim
            config_file_repo_location: apps/nvim/configs
          - filename: packer_init.lua
            config_file_location: ~/.config/nvim/lua
            config_file_repo_location: apps/nvim/configs/lua
          - filename: colors.lua
            config_file_location: ~/.config/nvim/lua/core
            config_file_repo_location: apps/nvim/configs/lua/core
          - filename: keymaps.lua
            config_file_location: ~/.config/nvim/lua/core
            config_file_repo_location: apps/nvim/configs/lua/core
          - filename: options.lua
            config_file_location: ~/.config/nvim/lua/core
            config_file_repo_location: apps/nvim/configs/lua/core
          - filename: telescope.lua
            config_file_location: ~/.config/nvim/after/plugin
            config_file_repo_location: apps/nvim/configs/after/plugin
          - filename: fugitive.lua
            config_file_location: ~/.config/nvim/after/plugin
            config_file_repo_location: apps/nvim/configs/after/plugin
          - filename: treesitter.lua
            config_file_location: ~/.config/nvim/after/plugin
            config_file_repo_location: apps/nvim/configs/after/plugin
          - filename: undotree.lua
            config_file_location: ~/.config/nvim/after/plugin
            config_file_repo_location: apps/nvim/configs/after/plugin
          - filename: dap.lua
            config_file_location: ~/.config/nvim/after/plugin
            config_file_repo_location: apps/nvim/configs/after/plugin
    - name: dnf
      config_files: 
          - filename: dnf.conf
            config_file_location: /etc/dnf
            config_file_repo_location: apps/dnf
