repo_root_path: /home/mk/hobby/gitrepo/mkos
app_details:
    - name: config manager
      config_files: 
          - filename: config.yml
            config_file_location: ~/.config/config_manager
            config_file_repo_location: configs/config_manager
    - name: alacritty
      config_files: 
          - filename: alacritty.yml
            config_file_location: ~/.config/alacritty
            config_file_repo_location: configs/config_manager
    - name: dnf
      config_files: 
          - filename: dnf.conf
            config_file_location: /etc/dnf
            config_file_repo_location: configs/dnf
