repo_root_path: /home/mk/hobby/gitrepo/mkos
app_details:
    - name: test app 1
      config_root_location: /home/mk/hobby/gitrepo/mkos/config_manager/test_files/config_location/app_1
      repo_root_location: config_manager/test_files/app_1
      config_files: 
          - filename: A
            config_file_location: /home/mk/hobby/gitrepo/mkos/config_manager/test_files/config_location/app_1
            config_file_repo_location: config_manager/test_files/app_1
          - filename: B
            config_file_location: /home/mk/hobby/gitrepo/mkos/config_manager/test_files/config_location/app_1
            config_file_repo_location: config_manager/test_files/app_1
          - filename: C
            config_file_location: /home/mk/hobby/gitrepo/mkos/config_manager/test_files/config_location/app_1
            config_file_repo_location: config_manager/test_files/app_1
    # - name: app1
    #   config_root_location: /home/mk/hobby/gitrepo/mkos/config_manager/test_files/config_location/app_2
    #   repo_root_location: config_manager/test_files/app_2
    #   config_files: 
    #     - Aw
    #     - Bw
    #     - Cw
    # - name: app2
    #   config_root_location: /home/mk/hobby/gitrepo/mkos/config_manager/test_files/config_location/app_3
    #   repo_root_location: config_manager1/test_files/app_31
    #   config_files: 
    #     - Ae
    #     - Be
    #     - Ce
    